import { Announcement } from "@/types/announcementTypes";

export const announcementsData: Announcement[] = [
  {
    id: 1,
    title: "Tetil",
    publisher: "Filankesov Behmenkas",
    description: "Creadive baş ofisi əsas idarəetmə və əməliyyat mərkəzidir.",
    date: "2025-03-14",
    category: "General",
    priority: "medium",
    status: "active",
    attachments: [],
    readBy: [101, 102, 103],
    expirationDate: "2025-04-01",
    tags: ["İdarəetmə", "Ofis"],
    authorId: 1,
  },
  {
    id: 2,
    title: "Yeni Layihə Başladı",
    publisher: "Creadive Komandası",
    description: "Yeni müştəri üçün veb sayt layihəsinə start verildi.",
    date: "2025-03-12",
    category: "Project",
    priority: "high",
    status: "active",
    attachments: ["https://example.com/project-details.pdf"],
    readBy: [104, 105, 106],
    expirationDate: "2025-03-30",
    tags: ["Yeni Layihə", "Veb Dizayn"],
    authorId: 2,
  },
  {
    id: 3,
    title: "İllik Hesabat",
    publisher: "Maliyyə Departamenti",
    description: "Şirkətin illik maliyyə hesabatı təqdim olundu.",
    date: "2025-02-28",
    category: "Finance",
    priority: "high",
    status: "archived",
    attachments: ["https://example.com/annual-report.pdf"],
    readBy: [101, 107, 108],
    expirationDate: "2025-04-01",
    tags: ["Hesabat", "Maliyyə"],
    authorId: 3,
  },
  {
    id: 4,
    title: "İş Saatlarında Dəyişiklik",
    publisher: "İnsan Resursları",
    description: "Yay mövsümü üçün yeni iş saatları elan edildi.",
    date: "2025-03-10",
    category: "HR",
    priority: "medium",
    status: "active",
    attachments: [],
    readBy: [102, 109, 110],
    expirationDate: "2025-09-01",
    tags: ["İş Saatı", "HR"],
    authorId: 4,
  },
  {
    id: 5,
    title: "Yeni İşçi Qoşuldu",
    publisher: "İnsan Resursları",
    description: "Komandamıza yeni dizayner əlavə olundu.",
    date: "2025-03-05",
    category: "HR",
    priority: "low",
    status: "active",
    attachments: [],
    readBy: [103, 111, 112],
    expirationDate: "2025-04-10",
    tags: ["İşçi", "Dizayn"],
    authorId: 4,
  },
  {
    id: 6,
    title: "Ofis Bağlıdır",
    publisher: "İdarə Heyəti",
    description: "Bazar günü texniki səbəblərdən ofis bağlı olacaq.",
    date: "2025-03-15",
    category: "General",
    priority: "medium",
    status: "active",
    attachments: [],
    readBy: [101, 104, 113],
    expirationDate: "2025-03-16",
    tags: ["Ofis", "Texniki"],
    authorId: 1,
  },
  {
    id: 7,
    title: "Təlim Keçiriləcək",
    publisher: "Təlim Departamenti",
    description:
      "Komanda üçün yeni marketinq strategiyaları üzrə seminar keçiriləcək.",
    date: "2025-03-07",
    category: "Training",
    priority: "high",
    status: "active",
    attachments: ["https://example.com/training-details.pdf"],
    readBy: [102, 105, 114],
    expirationDate: "2025-04-05",
    tags: ["Təlim", "Marketinq"],
    authorId: 5,
  },
  {
    id: 8,
    title: "Müştəri Məmnuniyyəti Sorğusu",
    publisher: "Marketinq Şöbəsi",
    description:
      "Müştərilərimizin rəyləri bizim üçün önəmlidir, sorğuda iştirak edin.",
    date: "2025-03-09",
    category: "Marketing",
    priority: "medium",
    status: "active",
    attachments: ["https://example.com/survey-link"],
    readBy: [103, 115, 116],
    expirationDate: "2025-04-10",
    tags: ["Müştəri", "Sorğu"],
    authorId: 6,
  },
  {
    id: 9,
    title: "Xəbərdarlıq: Təhlükəsizlik Problemi",
    publisher: "İT Departamenti",
    description: "Şirkət sistemində təhlükəsizlik yeniləmələri tətbiq edilir.",
    date: "2025-03-14",
    category: "IT",
    priority: "high",
    status: "active",
    attachments: ["https://example.com/security-update.pdf"],
    readBy: [101, 117, 118],
    expirationDate: "2025-03-31",
    tags: ["Təhlükəsizlik", "İT"],
    authorId: 7,
  },
  {
    id: 10,
    title: "Əməkdaşlar üçün Endirim Kampaniyası",
    publisher: "İnsan Resursları",
    description: "Bütün əməkdaşlar üçün xüsusi endirim kampaniyası aktivdir.",
    date: "2025-03-08",
    category: "HR",
    priority: "low",
    status: "active",
    attachments: [],
    readBy: [102, 119, 120],
    expirationDate: "2025-05-01",
    tags: ["Endirim", "İşçi"],
    authorId: 4,
  },
  {
    id: 11,
    title: "Yeni Avadanlıqlar Gəldi",
    publisher: "İT Departamenti",
    description: "Yeni kompüter və texniki avadanlıqlar ofisə gətirildi.",
    date: "2025-03-06",
    category: "IT",
    priority: "medium",
    status: "active",
    attachments: ["https://example.com/new-equipment-list.pdf"],
    readBy: [101, 121, 122],
    expirationDate: "2025-06-01",
    tags: ["İT", "Avadanlıq"],
    authorId: 7,
  },
  {
    id: 12,
    title: "İllik Şirkət Tədbiri",
    publisher: "İdarə Heyəti",
    description: "İllik şirkət tədbiri gələn ay keçiriləcək.",
    date: "2025-03-04",
    category: "Event",
    priority: "high",
    status: "active",
    attachments: ["https://example.com/event-details.pdf"],
    readBy: [101, 123, 124],
    expirationDate: "2025-04-15",
    tags: ["Tədbir", "Şirkət"],
    authorId: 1,
  },
];
