import { Employee } from "@/types/employeesTypes";

export const employeesData: Employee[] = [
  {
    id: 1,
    name: "Nihad Abbasov",
    position: "Təsisçi və Baş Direktor",
    email: "nihadabbasov@creadive.az",
    phone: "+994 55 777 77 77",
    bio: "Nihad Abbasov, Creadive şirkətinin təsisçisi və baş direktoru olaraq, biznes idarəçiliyi və inkişafı sahəsində 15 illik təcrübəyə malikdir. O, innovativ həllər və strateji rəhbərlik vasitəsilə şirkəti uğura çatdırır.",
    image: "/pp.png",
  },
  {
    id: 2,
    name: "Ənvər Nağıyev",
    position: "Marketinq Meneceri",
    email: "envernaghiyev@creadive.az",
    phone: "+994 50 111 11 11",
    bio: "Ənvər Nağıyev, 10 illik təcrübəsi olan bir marketinq mütəxəssisidir. O, brend strategiyaları və marketinq kampaniyalarını inkişaf etdirməkdə ixtisaslaşıb.",
    image: null,
  },
  {
    id: 3,
    name: "Alış Həziyev",
    position: "Əməliyyat Meneceri",
    email: "alishheziyev@creadive.az",
    phone: "+994 55 222 22 22",
    bio: "Alış Həziyev, əməliyyat idarəetməsi sahəsində 8 illik təcrübəyə malikdir. O, komanda idarəetməsi və layihələrin effektiv icrası üzrə mütəxəssisdir.",
    image: "/pp.png",
  },
  {
    id: 4,
    name: "Hüseyn İsmayılov",
    position: "Kontent Kreator",
    email: "huseynismayilov@creadive.az",
    phone: "+994 70 333 33 33",
    bio: "Hüseyn İsmayılov, kreativ məzmun yaratmaq və sosial media idarəetməsi üzrə 5 illik təcrübəyə malikdir. Onun işi daim yeniliklər gətirir və yüksək nəticələr əldə edir.",
    image: null,
  },
  {
    id: 5,
    name: "Fuad Şahbazov",
    position: "UX/UI Dizayner",
    email: "fuadshahbazov@creadive.az",
    phone: "+994 70 444 44 44",
    bio: "Fuad Şahbazov, müasir istifadəçi təcrübəsi və interfeysləri dizayn etmək üzrə 6 illik təcrübəyə malikdir. O, Adobe XD, Figma və Sketch-də mükəmməl nəticələr əldə edir.",
    image: null,
  },
  {
    id: 6,
    name: "Nihad Abduləlizadə",
    position: "Kreativ Dizayner/NoCode Developer",
    email: "nihadabdulalizade@creadive.az",
    phone: "+994 70 555 55 55",
    bio: "Nihad Abduləlizadə, kreativ dizayn və no-code platformaları ilə inkişaf etdirilən həllər üzrə ixtisaslaşıb. O, sürətli prototipləmə və estetik baxımdan cəlbedici layihələr yaradır.",
    image: "/pp.png",
  },
  {
    id: 7,
    name: "Şahsultan Nərgiz Səlimi",
    position: "Qrafik Dizayner",
    email: "shahsultannergizi@creadive.az",
    phone: "+994 70 666 66 66",
    bio: "Şahsultan Nərgiz Səlimi, qrafik dizayn üzrə 7 illik təcrübəyə malikdir. O, kreativ və cəlbedici vizuallar yaratmaq üçün Photoshop və Illustrator-da mükəmməldir.",
    image: "/pp.png",
  },
  {
    id: 8,
    name: "Rahib Məmmədov",
    position: "Qrafik Dizayner",
    email: "rahibmammadov@creadive.az",
    phone: "+994 70 888 88 88",
    bio: "Rahib Məmmədov, qrafik dizayn sahəsində 4 illik təcrübəyə malikdir. Kreativ dizayn konseptləri və rəqəmsal marketinq vizualları üzrə ixtisaslaşıb.",
    image: "/pp.png",
  },
  {
    id: 9,
    name: "Fuad Hüseynov",
    position: "Backend Developer",
    email: "fuadhuseynov@creadive.az",
    phone: "+994 55 999 99 99",
    bio: "Fuad Hüseynov, backend proqramlaşdırma və məlumat bazaları üzrə 6 illik təcrübəyə malikdir. Node.js, PostgreSQL və REST API inkişafı sahəsində mütəxəssisdir.",
    image: null,
  },
  {
    id: 10,
    name: "Jalə Pişyari",
    position: "UX/UI Dizayner",
    email: "jalepishyari@creadive.az",
    phone: "+994 50 777 77 77",
    bio: "Jalə Pişyari, istifadəçi təcrübəsi və interfeys dizaynı sahəsində 5 illik təcrübəyə malikdir. O, istifadəçi dostu interfeyslərin yaradılması ilə məşğul olur və müasir dizayn trendlərinə diqqət yetirir.",
    image: null,
  },
  {
    id: 11,
    name: "Asiman Loremzadə",
    position: "Kontent Kreator/Reels Maker",
    email: "asimanloremzade@creadive.az",
    phone: "+994 70 123 45 67",
    bio: "Asiman Loremzadə, yüksək keyfiyyətli və kreativ reels videoları hazırlamaq üzrə ixtisaslaşıb. O, vizual hekayələr yaratmaq və auditoriyanı cəlb etmək üçün innovativ yanaşma tətbiq edir.",
    image: "/pp.png",
  },
];
