// Mock Clients
export const clients = [
  {
    id: 1,
    name: "AzTexno MMC",
    description: "Sənaye istehsalı və logistika həlləri üzrə qlobal lider.",
    industry: "İstehsalat",
    contactPerson: "Cavid Əliyev",
    email: "cavid.aliyev@aztexno.az",
    phoneNumber: "+994-50-123-45-67",
    revenueGenerated: 500000,
    status: "Aktiv",
    website: "https://www.aztexno.az",
    lastInteractionDate: "2024-06-15",
    notes: "test",
    preferredCommunicationMethod: "Email",
    clientType: "Uzunmüddətli",
  },
  {
    id: 2,
    name: "Globus Texnologiya",
    description: "Proqram təminatı həllərində ixtisaslaşmış beynəlxalq şirkət.",
    industry: "Texnologiya",
    contactPerson: "Aytən Məmmədova",
    email: "ayten.m@globustech.az",
    phoneNumber: "+994-55-987-65-43",
    revenueGenerated: 750000,
    status: "Aktiv",
    website: "https://www.globustech.az",
    lastInteractionDate: "2024-06-10",
    notes: "test",
    preferredCommunicationMethod: "Telefon",
    clientType: "Qayıdan",
  },
  {
    id: 3,
    name: "Sağlam Həyat MMC",
    description:
      "Tibb və biotexnologiya sahəsində innovativ araşdırmalar aparan şirkət.",
    industry: "Səhiyyə",
    contactPerson: "Fərid Abbasov",
    email: "farid.abbasov@saglam.az",
    phoneNumber: "+994-12-789-12-34",
    revenueGenerated: 300000,
    status: "Gözləmədə",
    website: "https://www.saglam.az",
    lastInteractionDate: "2024-06-20",
    notes: "test",
    preferredCommunicationMethod: "Email",
    clientType: "Yeni",
  },
  {
    id: 4,
    name: "İnnovasiya Texnologiyaları",
    description: "Texnologiya və mühəndislik sahəsində qabaqcıl şirkət.",
    industry: "Mühəndislik",
    contactPerson: "Rəşad Həsənov",
    email: "rashad.h@innovasiya.az",
    phoneNumber: "+994-51-IRONMAN",
    revenueGenerated: 1200000,
    status: "Aktiv",
    website: "https://www.innovasiya.az",
    lastInteractionDate: "2024-06-05",
    notes: "test",
    preferredCommunicationMethod: "Telefon",
    clientType: "Uzunmüddətli",
  },
  {
    id: 5,
    name: "Qarabağ İnşaat",
    description:
      "Müdafiə, aviasiya və infrastruktur layihələrində ixtisaslaşmış şirkət.",
    industry: "Müdafiə",
    contactPerson: "Əli Hüseynov",
    email: "eli.huseynov@qarabag.az",
    phoneNumber: "+994-70-456-78-90",
    revenueGenerated: 950000,
    status: "Aktiv",
    website: "https://www.qarabag.az",
    lastInteractionDate: "2024-06-18",
    notes: "test",
    preferredCommunicationMethod: "Email",
    clientType: "Qayıdan",
  },
  {
    id: 6,
    name: "BioGen Araşdırma",
    description:
      "Genetik tədqiqat və texnologiyada müasir həllər təqdim edən şirkət.",
    industry: "Biotexnologiya",
    contactPerson: "Leyla Rzayeva",
    email: "leyla.rzayeva@biogen.az",
    phoneNumber: "+994-50-345-67-89",
    revenueGenerated: 400000,
    status: "Gözləmədə",
    website: "https://www.biogen.az",
    lastInteractionDate: "2024-06-12",
    notes: "test",
    preferredCommunicationMethod: "Telefon",
    clientType: "Yeni",
  },
  {
    id: 7,
    name: "DataKom",
    description:
      "Məlumat saxlama və sıxma sahəsində innovativ texnologiya şirkəti.",
    industry: "Proqram təminatı",
    contactPerson: "Kamran Nəsibov",
    email: "kamran.nasibov@datakom.az",
    phoneNumber: "+994-55-PIEDPIPER",
    revenueGenerated: 200000,
    status: "Aktiv",
    website: "https://www.datakom.az",
    lastInteractionDate: "2024-06-14",
    notes: "test",
    preferredCommunicationMethod: "Email",
    clientType: "Yeni",
  },
  {
    id: 8,
    name: "EnerjiTexno",
    description:
      "Enerji həlləri və dayanıqlı inkişaf sahəsində fəaliyyət göstərən şirkət.",
    industry: "Enerji",
    contactPerson: "Nigar Məmmədli",
    email: "nigar.m@enerjitekno.az",
    phoneNumber: "+994-55-654-32-10",
    revenueGenerated: 600000,
    status: "Aktiv",
    website: "https://www.enerjitekno.az",
    lastInteractionDate: "2024-06-22",
    notes: "test",
    preferredCommunicationMethod: "Telefon",
    clientType: "Uzunmüddətli",
  },
  {
    id: 9,
    name: "AvtoSənaye MMC",
    description:
      "Avtomobil istehsalı və sənaye texnologiyalarında ixtisaslaşmış şirkət.",
    industry: "Avtomobil",
    contactPerson: "Orxan Quliyev",
    email: "orxan.guliyev@avtosanaye.az",
    phoneNumber: "+994-50-789-10-11",
    revenueGenerated: 850000,
    status: "Gözləmədə",
    website: "https://www.avtosanaye.az",
    lastInteractionDate: "2024-06-25",
    notes: "test",
    preferredCommunicationMethod: "Email",
    clientType: "Yeni",
  },
  {
    id: 10,
    name: "Sürətli Kuryer",
    description:
      "Logistika və çatdırılma sahəsində yüksək sürətli xidmətlər təklif edən şirkət.",
    industry: "Logistika",
    contactPerson: "Elçin Sadıqov",
    email: "elchin.sadiqov@suratlikuryer.az",
    phoneNumber: "+994-55-567-89-01",
    revenueGenerated: 450000,
    status: "Aktiv",
    website: "https://www.suratlikuryer.az",
    lastInteractionDate: "2024-06-28",
    notes: "test",
    preferredCommunicationMethod: "Telefon",
    clientType: "Qayıdan",
  },
];

// Mock Orders
export const orders = [
  {
    id: 1,
    taskName: "Design New Logo",
    description: "Create a modern logo for Acme Corp.",
    priority: "High",
    assignee: "John Doe",
    startDate: "01.01.2024",
    dueDate: "15.01.2024",
    status: "Pending",
    comments: "Initial draft needed by next week.",
    clientId: 1,
  },
  {
    id: 2,
    taskName: "Website Redesign",
    description: "Complete redesign of Globex's website.",
    priority: "Medium",
    assignee: "Jane Smith",
    startDate: "05.01.2024",
    dueDate: "02.10.2024",
    status: "In Progress",
    comments: "Homepage wireframe completed.",
    clientId: 2,
  },
  {
    id: 3,
    taskName: "Mobile App Development",
    description: "Build a cross-platform app for Umbrella Ltd.",
    priority: "High",
    assignee: "Alice Brown",
    startDate: "10.01.2024",
    dueDate: "30.03.2024",
    status: "Pending",
    comments: "Focus on user-friendly UI.",
    clientId: 3,
  },
  {
    id: 4,
    taskName: "SEO Optimization",
    description: "Improve search engine ranking for Stark Industries.",
    priority: "Low",
    assignee: "Bob White",
    startDate: "15.01.2024",
    dueDate: "20.02.2024",
    status: "In Progress",
    comments: "Analyze keywords and backlinks.",
    clientId: 4,
  },
  {
    id: 5,
    taskName: "Security Audit",
    description: "Perform a security audit for Wayne Enterprises.",
    priority: "High",
    assignee: "Charlie Green",
    startDate: "18.01.2024",
    dueDate: "25.01.2024",
    status: "Completed",
    comments: "Audit report delivered.",
    clientId: 5,
  },
  {
    id: 6,
    taskName: "Product Launch Campaign",
    description: "Launch campaign for Oscorp's new product line.",
    priority: "Medium",
    assignee: "Diana King",
    startDate: "20.01.2024",
    dueDate: "10.02.2024",
    status: "Pending",
    comments: "Social media ads in progress.",
    clientId: 6,
  },
  {
    id: 7,
    taskName: "Backend API Development",
    description: "Build scalable APIs for Pied Piper's platform.",
    priority: "High",
    assignee: "Edward Taylor",
    startDate: "25.01.2024",
    dueDate: "30.04.2024",
    status: "Pending",
    comments: "Focus on performance optimization.",
    clientId: 7,
  },
];
